const CUSTOMER = {
  CUSTOMER_LIST: "CUSTOMER_LIST",
  CUSTOMER_LIST_SUCCESS: "CUSTOMER_LIST_SUCCESS",
  CUSTOMER_LIST_FAILED: "CUSTOMER_LIST_FAILED",
  CUSTOMER_FIRST: "CUSTOMER_FIRST",
  CUSTOMER_FIRST_SUCCESS: "CUSTOMER_FIRST_SUCCESS",
  CUSTOMER_FIRST_FAILED: "CUSTOMER_FIRST_FAILED",
  CUSTOMER_PUT: "CUSTOMER_PUT",
  CUSTOMER_PUT_SUCCESS: "CUSTOMER_PUT_SUCCESS",
  CUSTOMER_PUT_FAILED: "CUSTOMER_PUT_FAILED",
  CUSTOMER_POST: "CUSTOMER_POST",
  CUSTOMER_POST_SUCCESS: "CUSTOMER_POST_SUCCESS",
  CUSTOMER_POST_FAILED: "CUSTOMER_POST_FAILED",
  CUSTOMER_DELETE: "CUSTOMER_DELETE",
  CUSTOMER_DELETE_SUCCESS: "CUSTOMER_DELETE_SUCCESS",
  CUSTOMER_DELETE_FAILED: "CUSTOMER_DELETE_FAILED",
};

export default CUSTOMER;
