const CUSTOMER = {
  CUSTOMER_LIST: "CUSTOMER_LIST",
  CUSTOMER_LIST_SUCCESS: "CUSTOMER_LIST_SUCCESS",
  CUSTOMER_LIST_FAILED: "CUSTOMER_LIST_FAILED",
  CUSTOMER_DETAIL: "CUSTOMER_DETAIL",
  CUSTOMER_DETAIL_SUCCESS: "CUSTOMER_DETAIL_SUCCESS",
  CUSTOMER_DETAIL_FAILED: "CUSTOMER_DETAIL_FAILED",
  CUSTOMER_UPDATE: "CUSTOMER_UPDATE",
  CUSTOMER_UPDATE_SUCCESS: "CUSTOMER_UPDATE_SUCCESS",
  CUSTOMER_UPDATE_FAILED: "CUSTOMER_UPDATE_FAILED",
  CUSTOMER_CREATE: "CUSTOMER_CREATE",
  CUSTOMER_CREATE_SUCCESS: "CUSTOMER_CREATE_SUCCESS",
  CUSTOMER_CREATE_FAILED: "CUSTOMER_CREATE_FAILED",
  CUSTOMER_DELETE: "CUSTOMER_DELETE",
  CUSTOMER_DELETE_SUCCESS: "CUSTOMER_DELETE_SUCCESS",
  CUSTOMER_DELETE_FAILED: "CUSTOMER_DELETE_FAILED",
  CUSTOMER_STATUS: "CUSTOMER_STATUS",
  CUSTOMER_STATUS_SUCCESS: "CUSTOMER_STATUS_SUCCESS",
  CUSTOMER_STATUS_FAILED: "CUSTOMER_STATUS_FAILED",
};

export default CUSTOMER;
