const ServiceRequest = {
    // Create
    SERVICE_REQUEST_CREATE: "SERVICE_REQUEST_CREATE",
    SERVICE_REQUEST_CREATE_SUCCESS: "SERVICE_REQUEST_CREATE_SUCCESS",
    SERVICE_REQUEST_CREATE_FAILED: "SERVICE_REQUEST_CREATE_FAILED",
    // List 
    SERVICE_REQUEST_LIST: "SERVICE_REQUEST_LIST",
    SERVICE_REQUEST_LIST_SUCCESS: "SERVICE_REQUEST_LIST_SUCCESS",
    SERVICE_REQUEST_LIST_FAILED: "SERVICE_REQUEST_LIST_FAILED",
    // Detail 
    SERVICE_REQUEST_DETAIL: "SERVICE_REQUEST_DETAIL",
    SERVICE_REQUEST_DETAIL_SUCCESS: "SERVICE_REQUEST_DETAIL_SUCCESS",
    SERVICE_REQUEST_DETAIL_FAILED: "SERVICE_REQUEST_DETAIL_FAILED",
    // Status 
    SERVICE_REQUEST_STATUS: "SERVICE_REQUEST_STATUS",
    SERVICE_REQUEST_STATUS_SUCCESS: "SERVICE_REQUEST_STATUS_SUCCESS",
    SERVICE_REQUEST_STATUS_FAILED: "SERVICE_REQUEST_STATUS_FAILED",
}

export default ServiceRequest;