const VERIFICATION = {
    POST_VERIFICATION: "POST_VERIFICATION",
    POST_VERIFICATION_SUCCESS: "POST_VERIFICATION_SUCCESS",
    POST_VERIFICATION_FAILED: "POST_VERIFICATION_FAILED",
};

export default VERIFICATION;
