const CUSTOMER_BILLING_INFORMATION = {
  CUSTOMER_BILLING_INFORMATION_LIST: "CUSTOMER_BILLING_INFORMATION_LIST",
  CUSTOMER_BILLING_INFORMATION_LIST_SUCCESS: "CUSTOMER_BILLING_INFORMATION_LIST_SUCCESS",
  CUSTOMER_BILLING_INFORMATION_LIST_FAILED: "CUSTOMER_BILLING_INFORMATION_LIST_FAILED",
};

export default CUSTOMER_BILLING_INFORMATION;
