const Service = {
    // List 
    CUSTOMER_SERVICE_LIST: "CUSTOMER_SERVICE_LIST",
    CUSTOMER_SERVICE_LIST_SUCCESS: "CUSTOMER_SERVICE_LIST_SUCCESS",
    CUSTOMER_SERVICE_LIST_FAILED: "CUSTOMER_SERVICE_LIST_FAILED",
    // PAGINATION 
    CUSTOMER_SERVICE_PAGINATION: "CUSTOMER_SERVICE_PAGINATION",
    CUSTOMER_SERVICE_PAGINATION_SUCCESS: "CUSTOMER_SERVICE_PAGINATION_SUCCESS",
    CUSTOMER_SERVICE_PAGINATION_FAILED: "CUSTOMER_SERVICE_PAGINATION_FAILED",
}

export default Service;