const CUSTOMER_REGISTER = {
    CUSTOMER_POST_REGISTRATION: "CUSTOMER_POST_REGISTRATION",
    CUSTOMER_POST_REGISTRATION_SUCCESS: "CUSTOMER_POST_REGISTRATION_SUCCESS",
    CUSTOMER_POST_REGISTRATION_FAILED: "CUSTOMER_POST_REGISTRATION_FAILED",
};

export default CUSTOMER_REGISTER;
