const PORTAL_SETTING = {
    // Detail
    PORTAL_SETTING_DETAIL: "PORTAL_SETTING",
    PORTAL_SETTING_DETAIL_SUCCESS: "PORTAL_SETTING_SUCCESS",
    PORTAL_SETTING_DETAIL_FAILED: "PORTAL_SETTING_FAILED",
    // Edit 
    PORT_SETTING_UPDATE: "PORT_SETTING_UPDATE",
    PORT_SETTING_UPDATE_SUCCESS: "PORT_SETTING_UPDATE_SUCCESS",
    PORT_SETTING_UPDATE_FAILED: "PORT_SETTING_UPDATE_FAILED",
}

export default PORTAL_SETTING;