const PORTAL_SETTING = {
    // Detail
    PORTAL_SETTING_DETAIL: "PORTAL_SETTING_DETAIL",
    PORTAL_SETTING_DETAIL_SUCCESS: "PORTAL_SETTING_DETAIL_SUCCESS",
    PORTAL_SETTING_DETAIL_FAILED: "PORTAL_SETTING_DETAIL_FAILED",
    // Edit 
    PORTAL_SETTING_UPDATE: "PORTAL_SETTING_UPDATE",
    PORTAL_SETTING_UPDATE_SUCCESS: "PORTAL_SETTING_UPDATE_SUCCESS",
    PORTAL_SETTING_UPDATE_FAILED: "PORTAL_SETTING_UPDATE_FAILED",
}

export default PORTAL_SETTING;