const INVOICE = {
    // List 
    INVOICE_LIST: "INVOICE_LIST",
    INVOICE_LIST_SUCCESS: "INVOICE_LIST_SUCCESS",
    INVOICE_LIST_FAILED: "INVOICE_LIST_FAILED",
    // Delete
    INVOICE_DELETE: "INVOICE_DELETE",
    INVOICE_DELETE_SUCCESS: "INVOICE_DELETE_SUCCESS",
    INVOICE_DELETE_FAILED: "INVOICE_DELETE_FAILED",
    // Status 
    INVOICE_STATUS: "INVOICE_STATUS",
    INVOICE_STATUS_SUCCESS: "INVOICE_STATUS_SUCCESS",
    INVOICE_STATUS_FAILED: "INVOICE_STATUS_FAILED",
}

export default INVOICE;