const Service = {
    // Create
    SERVICE_CREATE: "SERVICE_CREATE",
    SERVICE_CREATE_SUCCESS: "SERVICE_CREATE_SUCCESS",
    SERVICE_CREATE_FAILED: "SERVICE_CREATE_FAILED",
    // List 
    SERVICE_LIST: "SERVICE_LIST",
    SERVICE_LIST_SUCCESS: "SERVICE_LIST_SUCCESS",
    SERVICE_LIST_FAILED: "SERVICE_LIST_FAILED",
}

export default Service;