const Service = {
    // Create
    SERVICE_CREATE: "SERVICE_CREATE",
    SERVICE_CREATE_SUCCESS: "SERVICE_CREATE_SUCCESS",
    SERVICE_CREATE_FAILED: "SERVICE_CREATE_FAILED",
    // List 
    SERVICE_LIST: "SERVICE_LIST",
    SERVICE_LIST_SUCCESS: "SERVICE_LIST_SUCCESS",
    SERVICE_LIST_FAILED: "SERVICE_LIST_FAILED",
    // Edit 
    SERVICE_EDIT: "SERVICE_EDIT",
    SERVICE_EDIT_SUCCESS: "SERVICE_EDIT_SUCCESS",
    SERVICE_EDIT_FAILED: "SERVICE_EDIT_FAILED",
    // Delete 
    SERVICE_DELETE: "SERVICE_DELETE",
    SERVICE_DELETE_SUCCESS: "SERVICE_DELETE_SUCCESS",
    SERVICE_DELETE_FAILED: "SERVICE_DELETE_FAILED",
    // PAGINATION 
    SERVICE_PAGINATION: "SERVICE_PAGINATION",
    SERVICE_PAGINATION_SUCCESS: "SERVICE_PAGINATION_SUCCESS",
    SERVICE_PAGINATION_FAILED: "SERVICE_PAGINATION_FAILED",
}

export default Service;