const PAYMENT_GATEWAY = {
    // Create
    PAYMENT_GATEWAY_CREATE: "PAYMENT_GATEWAY_CREATE",
    PAYMENT_GATEWAY_CREATE_SUCCESS: "PAYMENT_GATEWAY_CREATE_SUCCESS",
    PAYMENT_GATEWAY_CREATE_FAILED: "PAYMENT_GATEWAY_CREATE_FAILED",
    // Detail
    PAYMENT_GATEWAY_DETAIL: "PAYMENT_GATEWAY_DETAIL",
    PAYMENT_GATEWAY_DETAIL_SUCCESS: "PAYMENT_GATEWAY_DETAIL_SUCCESS",
    PAYMENT_GATEWAY_DETAIL_FAILED: "PAYMENT_GATEWAY_DETAIL_FAILED",
    // Status 
    PAYMENT_GATEWAY_STATUS: "PAYMENT_GATEWAY_STATUS",
    PAYMENT_GATEWAY_STATUS_SUCCESS: "PAYMENT_GATEWAY_STATUS_SUCCESS",
    PAYMENT_GATEWAY_STATUS_FAILED: "PAYMENT_GATEWAY_STATUS_FAILED",
}

export default PAYMENT_GATEWAY;