const PAYMENT_GATEWAY = {
    // Detail
    PAYMENT_GATEWAY_DETAIL: "PAYMENT_GATEWAY_DETAIL",
    PAYMENT_GATEWAY_DETAIL_SUCCESS: "PAYMENT_GATEWAY_DETAIL_SUCCESS",
    PAYMENT_GATEWAY_DETAIL_FAILED: "PAYMENT_GATEWAY_DETAIL_FAILED",
    // Edit 
    // PROFILE_SETTING_UPDATE: "PROFILE_SETTING_UPDATE",
    // PROFILE_SETTING_UPDATE_SUCCESS: "PROFILE_SETTING_UPDATE_SUCCESS",
    // PROFILE_SETTING_UPDATE_FAILED: "PROFILE_SETTING_UPDATE_FAILED",
}

export default PAYMENT_GATEWAY;