const PASSWORD_UPDATE = {
    // Edit 
    PASSWORD_UPDATE: "PASSWORD_UPDATE",
    PASSWORD_UPDATE_SUCCESS: "PASSWORD_UPDATE_SUCCESS",
    PASSWORD_UPDATE_FAILED: "PASSWORD_UPDATE_FAILED",
}

export default PASSWORD_UPDATE;