const LOGOUT_ACTION_TYPE = {
    DELETE_LOGOUT: "DELETE_LOGOUT",
    DELETE_LOGOUT_SUCCESS: "DELETE_LOGOUT_SUCCESS",
    DELETE_LOGOUT_FAILED: "DELETE_LOGOUT_FAILED",
};

export default LOGOUT_ACTION_TYPE;
