const SERVICE_REQUEST = {
    // Create
    CUSTOMER_SERVICE_REQUEST_CREATE: "CUSTOMER_SERVICE_REQUEST_CREATE",
    CUSTOMER_SERVICE_REQUEST_CREATE_SUCCESS: "CUSTOMER_SERVICE_REQUEST_CREATE_SUCCESS",
    CUSTOMER_SERVICE_REQUEST_CREATE_FAILED: "CUSTOMER_SERVICE_REQUEST_CREATE_FAILED",
    // List 
    CUSTOMER_SERVICE_REQUEST_LIST: "CUSTOMER_SERVICE_REQUEST_LIST",
    CUSTOMER_SERVICE_REQUEST_LIST_SUCCESS: "CUSTOMER_SERVICE_REQUEST_LIST_SUCCESS",
    CUSTOMER_SERVICE_REQUEST_LIST_FAILED: "CUSTOMER_SERVICE_REQUEST_LIST_FAILED",
    // Detail 
    CUSTOMER_SERVICE_REQUEST_DETAIL: "CUSTOMER_SERVICE_REQUEST_DETAIL",
    CUSTOMER_SERVICE_REQUEST_DETAIL_SUCCESS: "CUSTOMER_SERVICE_REQUEST_DETAIL_SUCCESS",
    CUSTOMER_SERVICE_REQUEST_DETAIL_FAILED: "CUSTOMER_SERVICE_REQUEST_DETAIL_FAILED",
    // Status 
    CUSTOMER_SERVICE_REQUEST_STATUS: "CUSTOMER_SERVICE_REQUEST_STATUS",
    CUSTOMER_SERVICE_REQUEST_STATUS_SUCCESS: "CUSTOMER_SERVICE_REQUEST_STATUS_SUCCESS",
    CUSTOMER_SERVICE_REQUEST_STATUS_FAILED: "CUSTOMER_SERVICE_REQUEST_STATUS_FAILED",
}

export default SERVICE_REQUEST;