const INVOICE = {
    // List 
    CUSTOMER_INVOICE_LIST: "CUSTOMER_INVOICE_LIST",
    CUSTOMER_INVOICE_LIST_SUCCESS: "CUSTOMER_INVOICE_LIST_SUCCESS",
    CUSTOMER_INVOICE_LIST_FAILED: "CUSTOMER_INVOICE_LIST_FAILED",
    // Detail 
    CUSTOMER_INVOICE_DETAIL: "CUSTOMER_INVOICE_DETAIL",
    CUSTOMER_INVOICE_DETAIL_SUCCESS: "CUSTOMER_INVOICE_DETAIL_SUCCESS",
    CUSTOMER_INVOICE_DETAIL_FAILED: "CUSTOMER_INVOICE_DETAIL_FAILED",
    // Invoice Paid 
    CUSTOMER_INVOICE_PAID: "CUSTOMER_INVOICE_PAID",
    CUSTOMER_INVOICE_PAID_SUCCESS: "CUSTOMER_INVOICE_PAID_SUCCESS",
    CUSTOMER_INVOICE_PAID_FAILED: "CUSTOMER_INVOICE_PAID_FAILED",
}

export default INVOICE;