const ForgotPassword = {
    POST_FORGOT_PASSWORD: "POST_FORGOT_PASSWORD",
    POST_FORGOT_PASSWORD_SUCCESS: "POST_FORGOT_PASSWORD_SUCCESS",
    POST_FORGOT_PASSWORD_FAILED: "POST_FORGOT_PASSWORD_FAILED",
};

export default ForgotPassword;
