const BILLING_INFORMATION = {
  BILLING_INFORMATION_DETAIL: "BILLING_INFORMATION_DETAIL",
  BILLING_INFORMATION_DETAIL_SUCCESS: "BILLING_INFORMATION_DETAIL_SUCCESS",
  BILLING_INFORMATION_DETAIL_FAILED: "BILLING_INFORMATION_DETAIL_FAILED",
  BILLING_INFORMATION_UPDATE: "BILLING_INFORMATION_UPDATE",
  BILLING_INFORMATION_UPDATE_SUCCESS: "BILLING_INFORMATION_UPDATE_SUCCESS",
  BILLING_INFORMATION_UPDATE_FAILED: "BILLING_INFORMATION_UPDATE_FAILED",
  BILLING_INFORMATION_CREATE: "BILLING_INFORMATION_CREATE",
  BILLING_INFORMATION_CREATE_SUCCESS: "BILLING_INFORMATION_CREATE_SUCCESS",
  BILLING_INFORMATION_CREATE_FAILED: "BILLING_INFORMATION_CREATE_FAILED",
};

export default BILLING_INFORMATION;
