const BILLING_INFORMATION = {
  BILLING_INFORMATION_LIST: "BILLING_INFORMATION_LIST",
  BILLING_INFORMATION_LIST_SUCCESS: "BILLING_INFORMATION_LIST_SUCCESS",
  BILLING_INFORMATION_LIST_FAILED: "BILLING_INFORMATION_LIST_FAILED",
  BILLING_INFORMATION_DETAIL: "BILLING_INFORMATION_DETAIL",
  BILLING_INFORMATION_DETAIL_SUCCESS: "BILLING_INFORMATION_DETAIL_SUCCESS",
  BILLING_INFORMATION_DETAIL_FAILED: "BILLING_INFORMATION_DETAIL_FAILED",
  BILLING_INFORMATION_CREATE: "BILLING_INFORMATION_CREATE",
  BILLING_INFORMATION_CREATE_SUCCESS: "BILLING_INFORMATION_CREATE_SUCCESS",
  BILLING_INFORMATION_CREATE_FAILED: "BILLING_INFORMATION_CREATE_FAILED",
  BILLING_INFORMATION_DELETE: "BILLING_INFORMATION_DELETE",
  BILLING_INFORMATION_DELETE_SUCCESS: "BILLING_INFORMATION_DELETE_SUCCESS",
  BILLING_INFORMATION_DELETE_FAILED: "BILLING_INFORMATION_DELETE_FAILED",
  MARK_PRIMARY: "MARK_PRIMARY",
  MARK_PRIMARY_SUCCESS: "MARK_PRIMARY_SUCCESS",
  MARK_PRIMARY_FAILED: "MARK_PRIMARY_FAILED",
};

export default BILLING_INFORMATION;
