const PROFILE_SETTING = {
    // Detail
    PROFILE_SETTING_DETAIL: "PROFILE_SETTING_DETAIL",
    PROFILE_SETTING_DETAIL_SUCCESS: "PROFILE_SETTING_DETAIL_SUCCESS",
    PROFILE_SETTING_DETAIL_FAILED: "PROFILE_SETTING_DETAIL_FAILED",
    // Edit 
    PROFILE_SETTING_UPDATE: "PROFILE_SETTING_UPDATE",
    PROFILE_SETTING_UPDATE_SUCCESS: "PROFILE_SETTING_UPDATE_SUCCESS",
    PROFILE_SETTING_UPDATE_FAILED: "PROFILE_SETTING_UPDATE_FAILED",
}

export default PROFILE_SETTING;