const REGISTER = {
    POST_REGISTRATION: "POST_REGISTRATION",
    POST_REGISTRATION_SUCCESS: "POST_REGISTRATION_SUCCESS",
    POST_REGISTRATION_FAILED: "POST_REGISTRATION_FAILED",
};

export default REGISTER;
